version: '3.8'

services:
  sqlserver2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433" # Exposes port 1433 to the host machine
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - sqlserver2022_data:/var/opt/mssql # Persistent data storage

volumes:
  sqlserver2022_data:
